# Generated by Django 4.0.6 on 2022-09-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
